# Generated by Django 4.2.15 on 2026-03-05 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('architecture', models.CharField(choices=[('lstm', 'LSTM'), ('gru', 'GRU'), ('bilstm', 'Bidirectional LSTM')], default='lstm', max_length=20)),
                ('sequence_length', models.PositiveIntegerField(default=100)),
                ('mc_iterations', models.PositiveIntegerField(default=50)),
                ('uncertainty_growth', models.FloatField(default=0.02)),
                ('default_confidence', models.FloatField(default=0.95)),
                ('technical_indicators', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=False)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('yfinance', 'Yahoo Finance (yfinance)'), ('alphavantage', 'Alpha Vantage'), ('finnhub', 'Finnhub')], max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('provider', models.CharField(default='yfinance', max_length=50)),
                ('future_days', models.PositiveIntegerField(default=0)),
                ('confidence_level', models.FloatField(default=0.95)),
                ('metrics', models.JSONField(default=dict)),
                ('prediction_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='api.modelconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'ticker'], name='api_predict_user_id_7ca3eb_idx'), models.Index(fields=['user', 'created_at'], name='api_predict_user_id_b5ccf6_idx')],
            },
        ),
    ]
